version: '3.7'
services:
    db:
        image: postgres
        ports:
          - 5432:5432
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: UM*3tAe<ns!q!nG3
    web:
        build: ./project
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - ./project:/usr/src/app
        ports:
            - 8000:8000