branch-defaults:
  master:
    environment: c-ds-driftly
    group_suffix: null
  mtoce:
    environment: driftly-ds-api-team
    group_suffix: null
environment-defaults:
  c-ds-api:
    branch: null
    repository: null
global:
  application_name: c-ds-driftly
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
